image: debian

stages:
  - build
  - release

build:
  stage: build
  before_script:
    - apt-get update && apt-get -qq install git make zip > /dev/null
  script:
    - make
  artifacts:
    name: "$CI_COMMIT_SHORT_SHA-$CI_JOB_NAME"
    paths:
      - build

release:
  stage: release
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  before_script:
    - apt-get update && apt-get -qq install zip > /dev/null
  script:
    - mv build/bemanitools-supplements.zip ./bemanitools-supplements.zip
    - find . -mindepth 1 ! -regex '^./bemanitools-supplements.zip' -delete
    - unzip bemanitools-supplements.zip
    - rm bemanitools-supplements.zip
  artifacts:
    name: "$CI_COMMIT_SHORT_SHA-$CI_JOB_NAME"
    paths:
      - ./*
